# Workflow name
name: 'Chromatic Deployment'

# Event for the workflow
on: push

# List of jobs
jobs:
  test;
    # Oprating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - run: yarn 
        # Adds chromatic as a step in the workflow
      - uses: chromaui/aciton@v1
        # Options required for chromatic's GitHub Action
        with:
          # Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/react/en/deploy to obtain it 
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
